#!/usr/bin/env python3

"""
  key-table -- Create table of key position / size
  Copyright (C) 2020 Dieter Baron

  This file is part of Anykey, a keyboard test program for C64.
  The authors can be contacted at <anykey@tpau.group>.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. The names of the authors may not be used to endorse or promote
     products derived from this software without specific prior
     written permission.

  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS
  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
  IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import sys

def write_word_table(tablename, table, fout):
	fout.write(f"{name}_{tablename}_low:\n");
	for value in table:
		fout.write("    .byte <(" + value + ")\n")
	fout.write("\n")
	fout.write(f"{name}_{tablename}_high:\n");
	for value in table:
		fout.write("    .byte >(" + value + ")\n")
	fout.write("\n")


if len(sys.argv) != 2:
     print("usage: ", sys.argv[0], " name-prefix\n")
     sys.exit(1)

name_prefix = sys.argv[1]

infile = name_prefix + ".key"
outfile = name_prefix + ".asm"

keys_screen = []
keys_color = []
keys_function = []
all_functions = {}

name = ""
offset_x = 0
offset_y = 0
key_width = 1
key_height = 1
screen_width = 32
lines_per_part = 8

with open(infile) as fin:
	for line in fin:
		comment = line.find(";")
		if comment > -1:
			line = line[0:comment]
		line.strip()
		words = line.split()
		if len(words) == 0:
			continue
		if words[0] == "name":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'name'")
			name = words[1]
		elif words[0] == "offset_x":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'offset_x'")
			offset_x = int(words[1])
		elif words[0] == "offset_y":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'offset_y'")
			offset_y = int(words[1])
		elif words[0] == "key_width":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'key_width'")
			key_width = int(words[1])
		elif words[0] == "key_height":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'key_height'")
			key_height = int(words[1])
		elif words[0] == "screen_width":
			if len(words) != 2:
				raise Exception("wrong number of arguments for 'screen_width'")
			screen_width = int(words[1])
		elif words[0] == "key":
			if len(words) != 4:
				raise Exception("wrong number of arguments for 'key'")
			x = int(words[1]) * key_width + offset_x
			y = int(words[2]) * key_height + offset_y
			f = "display_key_" + words[3]
			keys_screen.append("screen + " + str((y // lines_per_part) * screen_width * lines_per_part * 8 + (y % lines_per_part) * screen_width + x))
			keys_color.append("color + " + str(x + y * screen_width))
			keys_function.append(f)
			all_functions[f] = 1
		else:
			raise Exception("unknown command '" + words[0] + "'")

with open(outfile, mode="w") as fout:
	header = """; {outfile} -- keyboard layout {name}

; This file is automatically created by {program} from {infile}.
; Do not edit.

global keys_{name}, num_keys_{name}, {functions}

include "platform.inc"

section data_user

num_keys_{name}:
	byte {num_keys}

keys_{name}:
""".format(outfile=outfile, name=name, infile=infile, program=sys.argv[0], num_keys=len(keys_screen), functions=",".join(all_functions.keys()))
	fout.write(header)

	for i in range(len(keys_screen)):
		fout.write("    word " + keys_screen[i] + ", " + keys_color[i] + ", " + keys_function[i] + "\n")
