# input filename
image = "charset-8x16-2bit.png"
char_width = 8
char_height = 16

# output files
symbol_prefix = "charset_mega65_8x16"
output = "charset-mega65-8x16.s"

widths = [
    4, 4, 8, 8, 8, 8, 8, 4, 6, 6, 8, 6, 4, 6, 4, 8,
    8, 7, 6, 7, 8, 8, 8, 8, 8, 8, 4, 4, 6, 6, 6, 6,
    8, 8, 8, 7, 8, 8, 8, 8, 8, 4, 7, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 8, 6, 8, 8,
    4, 8, 8, 7, 8, 8, 7, 8, 8, 4, 7, 8, 4, 8, 8, 8,
    8, 8, 7, 8, 6, 8, 8, 8, 8, 8, 8, 7, 4, 7, 8, 8
]
