#!/usr/bin/env python3

import sys

import NCM


palette = {
    0xffffff: 1,
    0xA8A8A8: 2,
    0x545454: 3,
    0x000000: 4
}

if len(sys.argv) != 5:
    print("usage: ", sys.argv[0], " image charset char-width char-height\n")
    sys.exit(1)

image_file = sys.argv[1]
charset_file = sys.argv[2]
char_width = int(sys.argv[3])
char_height = int(sys.argv[4])

if char_height % 8 != 0:
    print("char-height must be multiple of 8")
    sys.exit(1)

data = b""

image = NCM.NCM(image_file, palette, char_width, 8, 1)

y_chars = char_height // 8

for char_y in range(0, y_chars):
    for y in range(0, image.height // y_chars):
        for x in range(0, image.width):
            data += image.get(x, y * y_chars + char_y)

with open(charset_file, "wb") as file:
    file.write(data)
