#!/usr/bin/env python3

"""
  convert-keyboard -- Convert keyboard bitmap to charsets.
  Copyright (C) 2020 Dieter Baron

  This file is part of Anykey, a keyboard test program for C64.
  The authors can be contacted at <anykey@tpau.group>.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
  2. The names of the authors may not be used to endorse or promote
     products derived from this software without specific prior
     written permission.

  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS
  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
  IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import sys

class Charset:
	def	__init__(self, size, empty):
		self.by_index = dict()
		self.by_value = dict()
		self.next_index = 0
		self.size = size
		self.empty = empty

	def add(self, value):
		if value in self.by_value:
			return self.by_value[value]
		else:
			index = self.get_next_index()
			self.by_value[value] = index
			self.by_index[index] = value
			return index

	def add_with_index(self, value, index):
		if index in self.by_index:
			raise RuntimeError("character already set")
		else:
			self.by_index[index] = value
			self.by_value[value] = index

	def get_next_index(self):
		while self.next_index in self.by_index:
			self.next_index += 1
			if self.next_index >= self.size:
				raise RuntimeError("out of characters")
		return self.next_index

	def get_values(self, index):
		if index in self.by_index:
			return self.by_index[index]
		else:
			return self.empty

def setup_charset(charset, top, bottom, rounded):
	charset.add_with_index((0, 0), 32)
	if top and rounded:
		charset.add_with_index((0xf0c0808000000000, 0xf0c0808000000000), 0x49)
		charset.add_with_index((0x0f03010100000000, 0x0f03010100000000), 0x4a)
	if bottom:
		if rounded:
			charset.add_with_index((0x0000008080c0f0ff, 0x0000008080c0f0ff), 0x4b)
			charset.add_with_index((0x0000000101030fff, 0x0000000101030fff), 0x4c)
		charset.add_with_index((0x00000000000000ff, 0x00000000000000ff), 0x4d)

def save_charset(charset, name):
	data = b""
	data_inv = b""
	for i in range(0, 128):
		pair = charset.get_values(i)
		data += pair[0].to_bytes(8, byteorder="big")
		data_inv += pair[1].to_bytes(8, byteorder="big")
	with open(name, "wb") as file:
		file.write(data)
		file.write(data_inv)

def save(data, name):
	with open(name, mode="wb") as file:
		file.write(data)

if len(sys.argv) != 4:
     print("usage: ", sys.argv[0], " name-prefix height split-line ...\n")
     sys.exit(1)

width = 40
name_prefix = sys.argv[1]
height = int(sys.argv[2])
top_lines = int(sys.argv[3])


screen = b""

with open(name_prefix + "-normal-bitmap.bin", mode='rb') as file_normal:
	with open(name_prefix + "-pressed-bitmap.bin", mode='rb') as file_pressed:
		for y in range(0, height):
			if y == 0:
				charset = Charset(128, (0, 0))
				setup_charset(charset, True, False, name_prefix != "keyboard-128")
			if y == top_lines:
				#print("------")
				save_charset(charset, name_prefix + "-charset-top.bin")
				charset = Charset(128, (0, 0))
				setup_charset(charset, False, True, name_prefix != "keyboard-128")
			for x in range(0, width):
				char_normal = int.from_bytes(file_normal.read(8), byteorder='big')
				char_pressed = int.from_bytes(file_pressed.read(8), byteorder='big')
				char = charset.add((char_normal, char_pressed))
				#print("(%02d, %02d): (%016x, %016x) -> %d" % (x, y, char_normal, char_pressed, char))
				screen += char.to_bytes(1, byteorder="big")

save_charset(charset, name_prefix + "-charset-bottom.bin")
save(screen, name_prefix + "-screen.bin")
